export const students = [
  {
    id: "1",
    programme: "frontend web developer",
    user: "jacky",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "jacky@gmail.com",
  },
  {
    id: "2",
    programme: "junior data engineer",
    user: "amy",
    company: "apple",
    position: "junior data engineer",
    phone: "1224547",
    email: "amy@gmail.com",
  },
  {
    id: "3",
    programme: "digital marketing",
    user: "tom",
    company: "meta",
    position: "junior digital marketing",
    phone: "5675423",
    email: "tom@gmail.com",
  },
  {
    id: "4",
    programme: "eldercare talent training",
    user: "ben",
    company: "Eldercare.hk",
    position: "junior eldercare",
    phone: "54565721",
    email: "ben@gmail.com",
  },
  {
    id: "5",
    programme: "quality assurance testing",
    user: "jason",
    company: "Master concept",
    position: "quality assurance assistant",
    phone: "53212453",
    email: "jason@gmail.com",
  },
  {
    id: "6",
    programme: "robot support assistant",
    user: "candy",
    company: "google",
    position: "robot support assistant",
    phone: "56233423",
    email: "candy@gmail.com",
  },
  {
    id: "7",
    programme: "customer experience and hospitality management",
    user: "karl",
    company: "abc comp",
    position: "customer experience and hospitality assistant",
    phone: "5632423",
    email: "karl@gmail.com",
  },
  {
    id: "8",
    programme: "customer experience and hospitality management",
    user: "tommy",
    company: "abc comp",
    position: "customer experience and hospitality assistant",
    phone: "5672394",
    email: "tommy@gmail.com",
  },
  {
    id: "9",
    programme: "eldercare talent training",
    user: "apple",
    company: "Eldercare.hk",
    position: "junior eldercare",
    phone: "56129853",
    email: "apple@gmail.com",
  },
  {
    id: "10",
    programme: "quality assurance testing",
    user: "kitty",
    company: "Master concept",
    position: "quality assurance assistant",
    phone: "5665423",
    email: "kitty@gmail.com",
  },
  {
    id: "11",
    programme: "robot support assistant",
    user: "hendy",
    company: "meta",
    position: "robot support assistant",
    phone: "5671123",
    email: "hendy@gmail.com",
  },
  {
    id: "12",
    programme: "eldercare talent training",
    user: "rainbow",
    company: "Eldercare.hk",
    position: "junior eldercare",
    phone: "5679921",
    email: "rainbow@gmail.com",
  },
  {
    id: "13",
    programme: "quality assurance testing",
    user: "wilson",
    company: "Master concept",
    position: "quality assurance assistant",
    phone: "5273612",
    email: "wilson@gmail.com",
  },
  {
    id: "14",
    programme: "customer experience and hospitality management",
    user: "sandy",
    company: "google",
    position: "customer experience and hospitality assistant",
    phone: "5238423",
    email: "sandy@gmail.com",
  },
  {
    id: "15",
    programme: "robot support assistant",
    user: "lowry",
    company: "google",
    position: "robot support assistant",
    phone: "562553",
    email: "lowry@gmail.com",
  },
];
