export const rows = [
    {
        id:'1',
        companyName:'Master concept',
        annualSalary:200000,
        title:'quality assurance assistant',
        workLocationArrangement:'office',
        requirements:'2 years',
        benefits:'birthday leave',
    },
    {
        id:'2',
        companyName:'Eldercare.hk',
        annualSalary:180000,
        title:'junior eldercare',
        workLocationArrangement:'onsite',
        requirements:'2 years',
        benefits:'birthday leave',
    },
    {
        id:'3',
        companyName:'google',
        annualSalary:200000,
        title:'robot support assistant',
        workLocationArrangement:'office',
        requirements:'2 years',
        benefits:'birthday leave',
    },
    {
        id:'4',
        companyName:'google',
        annualSalary:250000,
        title:'junior data engineer',
        workLocationArrangement:'office',
        requirements:'2 years',
        benefits:'birthday leave',
    },
    {
        id:'6',
        companyName:'google',
        annualSalary:200000,
        title:'robot support assistant',
        workLocationArrangement:'office',
        requirements:'2 years',
        benefits:'birthday leave',
    },
    {
        id:'7',
        companyName:'apple',
        annualSalary:250000,
        title:'junior programmer',
        workLocationArrangement:'office',
        requirements:'2 years',
        benefits:'birthday leave',
    },
    {
        id:'8',
        companyName: 'google',
        annualSalary:250000,
        title:'junior programmer',
        workLocationArrangement:'office',
        requirements:'2 years',
        benefits:'birthday leave',
    }
]