
export const rows =[
    {
        id:'1',
        employmentType:'full time',
        companyName:'cityline',
        salary:20000,
        dataPosted:'20/9/23',
        position:'junior frontend developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'2',
        employmentType:'full time',
        companyName:'A&A limited',
        salary:19000,
        dataPosted:'10/10/23',
        position:'junior web developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'3',
        employmentType:'full time',
        companyName:'OceanX',
        salary:21000,
        dataPosted:'13/9/23',
        position:'junior software developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'4',
        employmentType:'full time',
        companyName:'Mark Technology',
        salary:21000,
        dataPosted:'22/9/23',
        position:'Project Manager ',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'5',
        employmentType:'full time',
        companyName:'Master Concept',
        salary:18000,
        dataPosted:'1/9/23',
        position:' Programmer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'6',
        employmentType:'full time',
        companyName:'Master Concept',
        salary:20000,
        dataPosted:'10/9/23',
        position:'project officer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'7',
        employmentType:'full time',
        companyName:'google',
        salary:25000,
        dataPosted:'30/9/23',
        position:'junior developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    }
]