
export const rows =[
    {
        id:'1',
        companyName: 'google',
        annualSalary:250000,
        title:'junior programmer',
        workLocationArrangement:'office',
        requirements:'2 years',
        monthFromGraduation:3 ,
    },{
        id:'2',
        companyName:'apple',
        annualSalary:250000,
        title:'junior programmer',
        workLocationArrangement:'office',
        requirements:'2 years',
        monthFromGraduation:3 ,
    },{
        id:'3',
        companyName:'Master concept',
        annualSalary:200000,
        title:'quality assurance assistant',
        workLocationArrangement:'office',
        requirements:'2 years',
        monthFromGraduation:5 ,
    },{
        id:'4',
        companyName:'Eldercare.hk',
        annualSalary:180000,
        title:'junior eldercare',
        workLocationArrangement:'onsite',
        requirements:'2 years',
        monthFromGraduation:8 ,
    },{
        id:'5',
        companyName:'google',
        annualSalary:200000,
        title:'robot support assistant',
        workLocationArrangement:'office',
        requirements:'2 years',
        monthFromGraduation:2 ,
    },{
        id:'6',
        companyName:'amazon',
        annualSalary:260000,
        title:'junior digital marketing',
        workLocationArrangement:'office',
        requirements:'2 years',
        monthFromGraduation:3 ,
    },{
        id:'7',
        companyName:'google',
        annualSalary:250000,
        title:'junior data engineer',
        workLocationArrangement:'office',
        requirements:'2 years',
        monthFromGraduation:2 ,
    }
]