export const mockdataforchart = [
  {
    id: "1",
    programme: "front end web developer",
    user: "jacky",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "jacky@gmail.com",
    salary: 18000,
    fisrtjob: "1-3",
  },
  {
    id: "2",
    programme: "junior data engineer",
    user: "amy",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "amy@gmail.com",
    salary: 20000,
    fisrtjob: "3-6",
  },
  {
    id: "3",
    programme: "junior data engineer",
    user: "joe",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "joe@gmail.com",
    salary: 21000,
    fisrtjob: "1-3",
  },
  {
    id: "4",
    programme: "front end web developer",
    user: "ryan",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "ryan@gmail.com",
    salary: 30000,
    fisrtjob: "1-3",
  },
  {
    id: "5",
    programme: "front end web developer",
    user: "charlie",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "charlie@gmail.com",
    salary: 27000,
    fisrtjob: "1-3",
  },
  {
    id: "6",
    programme: "junior data engineer",
    user: "ben",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "ben@gmail.com",
    salary: 15000,
    fisrtjob: "6 or above",
  },
  {
    id: "7",
    programme: "junior data engineer",
    user: "danny",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "danny@gmail.com",
    salary: 19000,
    fisrtjob: "6 or above",
  },
  {
    id: "8",
    programme: "digital marketing",
    user: "kris",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "kris@gmail.com",
    salary: 16000,
    fisrtjob: "3-6",
  },
  {
    id: "9",
    programme: "front end web developer",
    user: "lisa",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "lisa@gmail.com",
    salary: 21000,
    fisrtjob: "3-6",
  },
  {
    id: "10",
    programme: "digital marketing",
    user: "carl",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "carl@gmail.com",
    salary: 20000,
    fisrtjob: "1-3",
  },
  {
    id: "11",
    programme: "digital marketing",
    user: "jason",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "jason@gmail.com",
    salary: 17000,
    fisrtjob: "6 or above",
  },
  {
    id: "12",
    programme: "digital marketing",
    user: "gordon",
    company: "google",
    position: "junior developer",
    phone: "1234567",
    email: "gordon@gmail.com",
    salary: 15000,
    fisrtjob: "1-3",
  },
];
